# Generated by Django 5.2.17 on 2026-09-14 17:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import pipeline.dates


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("watcher", "0005_job_key_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interest", "Interest"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("challenge", "Challenge"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="interest",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("applied_on", models.DateField(blank=True, null=True)),
                ("next_step", models.CharField(blank=True, default="", max_length=300)),
                ("next_step_on", models.DateField(blank=True, db_index=True, null=True)),
                ("contact", models.CharField(blank=True, default="", max_length=200)),
                ("has_referral", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="watcher.job",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(default=pipeline.dates.local_today)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="pipeline.application",
                    ),
                ),
            ],
            options={
                "db_table": "interactions",
            },
        ),
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("model", models.CharField(max_length=80)),
                ("instruction", models.CharField(blank=True, default="", max_length=300)),
                ("max_chars", models.PositiveIntegerField()),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("thinking_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="watcher.job",
                    ),
                ),
            ],
            options={
                "db_table": "pitches",
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status", "priority"], name="idx_applications_status"),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(fields=["application", "-date"], name="idx_interactions_app"),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(fields=["job", "-created_at"], name="idx_pitches_job"),
        ),
    ]
