# Generated by Django 5.2.17 on 2026-09-14 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("key", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("catch_up", "Catch Up"),
                            ("manual", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("companies_total", models.PositiveIntegerField(default=0)),
                ("companies_checked", models.PositiveIntegerField(default=0)),
                ("jobs_found", models.PositiveIntegerField(default=0)),
                ("jobs_new", models.PositiveIntegerField(default=0)),
                ("jobs_archived", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "check_runs",
                "indexes": [
                    models.Index(
                        fields=["status", "-finished_at"], name="idx_runs_status_finished"
                    ),
                    models.Index(fields=["-requested_at"], name="idx_runs_requested"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=500, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "companies",
                "indexes": [
                    models.Index(fields=["is_active", "is_removed"], name="idx_companies_active")
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckRunCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collecting", "Collecting"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("jobs", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_states",
                        to="watcher.checkrun",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_states",
                        to="watcher.company",
                    ),
                ),
            ],
            options={
                "db_table": "check_run_companies",
                "indexes": [
                    models.Index(fields=["run", "position"], name="idx_run_companies_position")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "company"), name="uniq_run_company")
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("url", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "archive_source",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("source", "Source")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("archive_reason", models.CharField(blank=True, max_length=32, null=True)),
                ("archive_note", models.TextField(blank=True, null=True)),
                ("is_highlighted", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("first_visited_at", models.DateTimeField(blank=True, null=True)),
                ("last_visited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="watcher.company",
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
                "indexes": [
                    models.Index(fields=["status", "-last_seen_at"], name="idx_jobs_status_seen"),
                    models.Index(
                        fields=["is_highlighted", "status"], name="idx_jobs_highlighted_status"
                    ),
                    models.Index(fields=["company", "status"], name="idx_jobs_company_status"),
                    models.Index(
                        fields=["status", "-is_new", "-first_seen_at"],
                        name="idx_jobs_listing_order",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "external_id"), name="uniq_jobs_company_external_id"
                    )
                ],
            },
        ),
    ]
